### PR TITLE
Added l as a valid localization function name

### PR DESCRIPTION
**Pull request by martingri**
It is to support the I18N plugin for Mojolicious.

### CODE REVIEW

**Comment by clintongormley** [comment]
Hiya Martin

Apologies for the slow response - I've been really busy.  If you could add tests for the above, I'd be happy to merge it

thanks

clint

**Comment by clintongormley** [comment]
@martingri  Any news on this?

**Comment by martingri** [comment]
Hey Clint.

Sorry about my late reply. I'll add a test for it. I couldn't find a test for the Perl plugin module, did I miss it or should I just create a new one?

**Comment by clintongormley** [comment]
Heya Martin.

You can add them to https://github.com/clintongormley/locale-maketext-lexicon/blob/master/t/51-perlextract.t
Or even copy/paste that file to a new file and rename the `_` to `l`

ta

clint

**Pull request closed without merging**
